// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventStatus int32

const (
	EventStatus_EVENT_STATUS_UNSPECIFIED EventStatus = 0
	EventStatus_EVENT_STATUS_UPCOMING    EventStatus = 1
	EventStatus_EVENT_STATUS_ONGOING     EventStatus = 2
	EventStatus_EVENT_STATUS_COMPLETED   EventStatus = 3
	EventStatus_EVENT_STATUS_CANCELLED   EventStatus = 4
)

// Enum value maps for EventStatus.
var (
	EventStatus_name = map[int32]string{
		0: "EVENT_STATUS_UNSPECIFIED",
		1: "EVENT_STATUS_UPCOMING",
		2: "EVENT_STATUS_ONGOING",
		3: "EVENT_STATUS_COMPLETED",
		4: "EVENT_STATUS_CANCELLED",
	}
	EventStatus_value = map[string]int32{
		"EVENT_STATUS_UNSPECIFIED": 0,
		"EVENT_STATUS_UPCOMING":    1,
		"EVENT_STATUS_ONGOING":     2,
		"EVENT_STATUS_COMPLETED":   3,
		"EVENT_STATUS_CANCELLED":   4,
	}
)

func (x EventStatus) Enum() *EventStatus {
	p := new(EventStatus)
	*p = x
	return p
}

func (x EventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (EventStatus) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x EventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventStatus.Descriptor instead.
func (EventStatus) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

// Event type for AI discovery search
type DiscoverEventType int32

const (
	DiscoverEventType_DISCOVER_EVENT_TYPE_UNSPECIFIED DiscoverEventType = 0
	DiscoverEventType_DISCOVER_EVENT_TYPE_CONCERT     DiscoverEventType = 1
	DiscoverEventType_DISCOVER_EVENT_TYPE_EXPOSITION  DiscoverEventType = 2
	DiscoverEventType_DISCOVER_EVENT_TYPE_FESTIVAL    DiscoverEventType = 3
	DiscoverEventType_DISCOVER_EVENT_TYPE_SPORT       DiscoverEventType = 4
	DiscoverEventType_DISCOVER_EVENT_TYPE_THEATRE     DiscoverEventType = 5
	DiscoverEventType_DISCOVER_EVENT_TYPE_GASTRONOMIE DiscoverEventType = 6
	DiscoverEventType_DISCOVER_EVENT_TYPE_MARCHE      DiscoverEventType = 7
	DiscoverEventType_DISCOVER_EVENT_TYPE_CINEMA      DiscoverEventType = 8
	DiscoverEventType_DISCOVER_EVENT_TYPE_CONFERENCE  DiscoverEventType = 9
	DiscoverEventType_DISCOVER_EVENT_TYPE_SOIREE      DiscoverEventType = 10
)

// Enum value maps for DiscoverEventType.
var (
	DiscoverEventType_name = map[int32]string{
		0:  "DISCOVER_EVENT_TYPE_UNSPECIFIED",
		1:  "DISCOVER_EVENT_TYPE_CONCERT",
		2:  "DISCOVER_EVENT_TYPE_EXPOSITION",
		3:  "DISCOVER_EVENT_TYPE_FESTIVAL",
		4:  "DISCOVER_EVENT_TYPE_SPORT",
		5:  "DISCOVER_EVENT_TYPE_THEATRE",
		6:  "DISCOVER_EVENT_TYPE_GASTRONOMIE",
		7:  "DISCOVER_EVENT_TYPE_MARCHE",
		8:  "DISCOVER_EVENT_TYPE_CINEMA",
		9:  "DISCOVER_EVENT_TYPE_CONFERENCE",
		10: "DISCOVER_EVENT_TYPE_SOIREE",
	}
	DiscoverEventType_value = map[string]int32{
		"DISCOVER_EVENT_TYPE_UNSPECIFIED": 0,
		"DISCOVER_EVENT_TYPE_CONCERT":     1,
		"DISCOVER_EVENT_TYPE_EXPOSITION":  2,
		"DISCOVER_EVENT_TYPE_FESTIVAL":    3,
		"DISCOVER_EVENT_TYPE_SPORT":       4,
		"DISCOVER_EVENT_TYPE_THEATRE":     5,
		"DISCOVER_EVENT_TYPE_GASTRONOMIE": 6,
		"DISCOVER_EVENT_TYPE_MARCHE":      7,
		"DISCOVER_EVENT_TYPE_CINEMA":      8,
		"DISCOVER_EVENT_TYPE_CONFERENCE":  9,
		"DISCOVER_EVENT_TYPE_SOIREE":      10,
	}
)

func (x DiscoverEventType) Enum() *DiscoverEventType {
	p := new(DiscoverEventType)
	*p = x
	return p
}

func (x DiscoverEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoverEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[1].Descriptor()
}

func (DiscoverEventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[1]
}

func (x DiscoverEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoverEventType.Descriptor instead.
func (DiscoverEventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

type RSVPStatus int32

const (
	RSVPStatus_RSVP_STATUS_UNSPECIFIED RSVPStatus = 0
	RSVPStatus_RSVP_STATUS_GOING       RSVPStatus = 1
	RSVPStatus_RSVP_STATUS_MAYBE       RSVPStatus = 2
	RSVPStatus_RSVP_STATUS_NOT_GOING   RSVPStatus = 3
)

// Enum value maps for RSVPStatus.
var (
	RSVPStatus_name = map[int32]string{
		0: "RSVP_STATUS_UNSPECIFIED",
		1: "RSVP_STATUS_GOING",
		2: "RSVP_STATUS_MAYBE",
		3: "RSVP_STATUS_NOT_GOING",
	}
	RSVPStatus_value = map[string]int32{
		"RSVP_STATUS_UNSPECIFIED": 0,
		"RSVP_STATUS_GOING":       1,
		"RSVP_STATUS_MAYBE":       2,
		"RSVP_STATUS_NOT_GOING":   3,
	}
)

func (x RSVPStatus) Enum() *RSVPStatus {
	p := new(RSVPStatus)
	*p = x
	return p
}

func (x RSVPStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RSVPStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[2].Descriptor()
}

func (RSVPStatus) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[2]
}

func (x RSVPStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RSVPStatus.Descriptor instead.
func (RSVPStatus) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	EventDate     string                 `protobuf:"bytes,4,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"` // Format: YYYY-MM-DD HH:MM
	Location      *string                `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Budget        *float64               `protobuf:"fixed64,6,opt,name=budget,proto3,oneof" json:"budget,omitempty"`
	FundId        *string                `protobuf:"bytes,7,opt,name=fund_id,json=fundId,proto3,oneof" json:"fund_id,omitempty"` // Link to common fund
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEventRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetEventDate() string {
	if x != nil {
		return x.EventDate
	}
	return ""
}

func (x *CreateEventRequest) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *CreateEventRequest) GetBudget() float64 {
	if x != nil && x.Budget != nil {
		return *x.Budget
	}
	return 0
}

func (x *CreateEventRequest) GetFundId() string {
	if x != nil && x.FundId != nil {
		return *x.FundId
	}
	return ""
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *GetEventRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Status        *EventStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=coloc.EventStatus,oneof" json:"status,omitempty"`
	StartDate     *string                `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate       *string                `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	Page          *int32                 `protobuf:"varint,5,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *ListEventsRequest) GetStatus() EventStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return EventStatus_EVENT_STATUS_UNSPECIFIED
}

func (x *ListEventsRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *ListEventsRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *ListEventsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListEventsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEventsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	EventDate     *string                `protobuf:"bytes,5,opt,name=event_date,json=eventDate,proto3,oneof" json:"event_date,omitempty"`
	Location      *string                `protobuf:"bytes,6,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Budget        *float64               `protobuf:"fixed64,7,opt,name=budget,proto3,oneof" json:"budget,omitempty"`
	FundId        *string                `protobuf:"bytes,8,opt,name=fund_id,json=fundId,proto3,oneof" json:"fund_id,omitempty"`
	Status        *EventStatus           `protobuf:"varint,9,opt,name=status,proto3,enum=coloc.EventStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEventRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetEventDate() string {
	if x != nil && x.EventDate != nil {
		return *x.EventDate
	}
	return ""
}

func (x *UpdateEventRequest) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *UpdateEventRequest) GetBudget() float64 {
	if x != nil && x.Budget != nil {
		return *x.Budget
	}
	return 0
}

func (x *UpdateEventRequest) GetFundId() string {
	if x != nil && x.FundId != nil {
		return *x.FundId
	}
	return ""
}

func (x *UpdateEventRequest) GetStatus() EventStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return EventStatus_EVENT_STATUS_UNSPECIFIED
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEventRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RSVPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        RSVPStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=coloc.RSVPStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RSVPRequest) Reset() {
	*x = RSVPRequest{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSVPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSVPRequest) ProtoMessage() {}

func (x *RSVPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSVPRequest.ProtoReflect.Descriptor instead.
func (*RSVPRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *RSVPRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *RSVPRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RSVPRequest) GetStatus() RSVPStatus {
	if x != nil {
		return x.Status
	}
	return RSVPStatus_RSVP_STATUS_UNSPECIFIED
}

type RSVPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RSVPResponse) Reset() {
	*x = RSVPResponse{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSVPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSVPResponse) ProtoMessage() {}

func (x *RSVPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSVPResponse.ProtoReflect.Descriptor instead.
func (*RSVPResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *RSVPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsRequest) Reset() {
	*x = GetParticipantsRequest{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsRequest) ProtoMessage() {}

func (x *GetParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsRequest.ProtoReflect.Descriptor instead.
func (*GetParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *GetParticipantsRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *GetParticipantsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*EventParticipant    `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	GoingCount    int32                  `protobuf:"varint,2,opt,name=going_count,json=goingCount,proto3" json:"going_count,omitempty"`
	MaybeCount    int32                  `protobuf:"varint,3,opt,name=maybe_count,json=maybeCount,proto3" json:"maybe_count,omitempty"`
	NotGoingCount int32                  `protobuf:"varint,4,opt,name=not_going_count,json=notGoingCount,proto3" json:"not_going_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsResponse) Reset() {
	*x = GetParticipantsResponse{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsResponse) ProtoMessage() {}

func (x *GetParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsResponse.ProtoReflect.Descriptor instead.
func (*GetParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *GetParticipantsResponse) GetParticipants() []*EventParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *GetParticipantsResponse) GetGoingCount() int32 {
	if x != nil {
		return x.GoingCount
	}
	return 0
}

func (x *GetParticipantsResponse) GetMaybeCount() int32 {
	if x != nil {
		return x.MaybeCount
	}
	return 0
}

func (x *GetParticipantsResponse) GetNotGoingCount() int32 {
	if x != nil {
		return x.NotGoingCount
	}
	return 0
}

type EventParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNom       string                 `protobuf:"bytes,2,opt,name=user_nom,json=userNom,proto3" json:"user_nom,omitempty"`
	UserPrenom    string                 `protobuf:"bytes,3,opt,name=user_prenom,json=userPrenom,proto3" json:"user_prenom,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	RsvpStatus    RSVPStatus             `protobuf:"varint,5,opt,name=rsvp_status,json=rsvpStatus,proto3,enum=coloc.RSVPStatus" json:"rsvp_status,omitempty"`
	RespondedAt   string                 `protobuf:"bytes,6,opt,name=responded_at,json=respondedAt,proto3" json:"responded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventParticipant) Reset() {
	*x = EventParticipant{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventParticipant) ProtoMessage() {}

func (x *EventParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventParticipant.ProtoReflect.Descriptor instead.
func (*EventParticipant) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *EventParticipant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventParticipant) GetUserNom() string {
	if x != nil {
		return x.UserNom
	}
	return ""
}

func (x *EventParticipant) GetUserPrenom() string {
	if x != nil {
		return x.UserPrenom
	}
	return ""
}

func (x *EventParticipant) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *EventParticipant) GetRsvpStatus() RSVPStatus {
	if x != nil {
		return x.RsvpStatus
	}
	return RSVPStatus_RSVP_STATUS_UNSPECIFIED
}

func (x *EventParticipant) GetRespondedAt() string {
	if x != nil {
		return x.RespondedAt
	}
	return ""
}

type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ColocationId    string                 `protobuf:"bytes,2,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedByNom    string                 `protobuf:"bytes,4,opt,name=created_by_nom,json=createdByNom,proto3" json:"created_by_nom,omitempty"`
	CreatedByPrenom string                 `protobuf:"bytes,5,opt,name=created_by_prenom,json=createdByPrenom,proto3" json:"created_by_prenom,omitempty"`
	Title           string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description     *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	EventDate       string                 `protobuf:"bytes,8,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`
	Location        *string                `protobuf:"bytes,9,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Budget          *float64               `protobuf:"fixed64,10,opt,name=budget,proto3,oneof" json:"budget,omitempty"`
	FundId          *string                `protobuf:"bytes,11,opt,name=fund_id,json=fundId,proto3,oneof" json:"fund_id,omitempty"`
	Status          EventStatus            `protobuf:"varint,13,opt,name=status,proto3,enum=coloc.EventStatus" json:"status,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Current user's RSVP
	UserRsvp RSVPStatus `protobuf:"varint,15,opt,name=user_rsvp,json=userRsvp,proto3,enum=coloc.RSVPStatus" json:"user_rsvp,omitempty"`
	// Participant counts
	GoingCount    int32 `protobuf:"varint,16,opt,name=going_count,json=goingCount,proto3" json:"going_count,omitempty"`
	MaybeCount    int32 `protobuf:"varint,17,opt,name=maybe_count,json=maybeCount,proto3" json:"maybe_count,omitempty"`
	NotGoingCount int32 `protobuf:"varint,18,opt,name=not_going_count,json=notGoingCount,proto3" json:"not_going_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *Event) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Event) GetCreatedByNom() string {
	if x != nil {
		return x.CreatedByNom
	}
	return ""
}

func (x *Event) GetCreatedByPrenom() string {
	if x != nil {
		return x.CreatedByPrenom
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Event) GetEventDate() string {
	if x != nil {
		return x.EventDate
	}
	return ""
}

func (x *Event) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *Event) GetBudget() float64 {
	if x != nil && x.Budget != nil {
		return *x.Budget
	}
	return 0
}

func (x *Event) GetFundId() string {
	if x != nil && x.FundId != nil {
		return *x.FundId
	}
	return ""
}

func (x *Event) GetStatus() EventStatus {
	if x != nil {
		return x.Status
	}
	return EventStatus_EVENT_STATUS_UNSPECIFIED
}

func (x *Event) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Event) GetUserRsvp() RSVPStatus {
	if x != nil {
		return x.UserRsvp
	}
	return RSVPStatus_RSVP_STATUS_UNSPECIFIED
}

func (x *Event) GetGoingCount() int32 {
	if x != nil {
		return x.GoingCount
	}
	return 0
}

func (x *Event) GetMaybeCount() int32 {
	if x != nil {
		return x.MaybeCount
	}
	return 0
}

func (x *Event) GetNotGoingCount() int32 {
	if x != nil {
		return x.NotGoingCount
	}
	return 0
}

// AI Event Discovery messages
type DiscoverEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	EventType     DiscoverEventType      `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=coloc.DiscoverEventType" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverEventsRequest) Reset() {
	*x = DiscoverEventsRequest{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverEventsRequest) ProtoMessage() {}

func (x *DiscoverEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverEventsRequest.ProtoReflect.Descriptor instead.
func (*DiscoverEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13}
}

func (x *DiscoverEventsRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *DiscoverEventsRequest) GetEventType() DiscoverEventType {
	if x != nil {
		return x.EventType
	}
	return DiscoverEventType_DISCOVER_EVENT_TYPE_UNSPECIFIED
}

type DiscoveredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Price         *float64               `protobuf:"fixed64,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Url           *string                `protobuf:"bytes,6,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveredEvent) Reset() {
	*x = DiscoveredEvent{}
	mi := &file_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredEvent) ProtoMessage() {}

func (x *DiscoveredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredEvent.ProtoReflect.Descriptor instead.
func (*DiscoveredEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14}
}

func (x *DiscoveredEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DiscoveredEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DiscoveredEvent) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DiscoveredEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *DiscoveredEvent) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *DiscoveredEvent) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *DiscoveredEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type DiscoverEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*DiscoveredEvent     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	SearchSummary string                 `protobuf:"bytes,2,opt,name=search_summary,json=searchSummary,proto3" json:"search_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverEventsResponse) Reset() {
	*x = DiscoverEventsResponse{}
	mi := &file_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverEventsResponse) ProtoMessage() {}

func (x *DiscoverEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverEventsResponse.ProtoReflect.Descriptor instead.
func (*DiscoverEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{15}
}

func (x *DiscoverEventsResponse) GetEvents() []*DiscoveredEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *DiscoverEventsResponse) GetSearchSummary() string {
	if x != nil {
		return x.SearchSummary
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x05coloc\x1a\x1cgoogle/api/annotations.proto\"\xa5\x02\n" +
	"\x12CreateEventRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"event_date\x18\x04 \x01(\tR\teventDate\x12\x1f\n" +
	"\blocation\x18\x05 \x01(\tH\x01R\blocation\x88\x01\x01\x12\x1b\n" +
	"\x06budget\x18\x06 \x01(\x01H\x02R\x06budget\x88\x01\x01\x12\x1c\n" +
	"\afund_id\x18\a \x01(\tH\x03R\x06fundId\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_locationB\t\n" +
	"\a_budgetB\n" +
	"\n" +
	"\b_fund_id\"F\n" +
	"\x0fGetEventRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xa6\x02\n" +
	"\x11ListEventsRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.coloc.EventStatusH\x00R\x06status\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tH\x01R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x04 \x01(\tH\x02R\aendDate\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x05 \x01(\x05H\x03R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x06 \x01(\x05H\x04R\bpageSize\x88\x01\x01B\t\n" +
	"\a_statusB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"\x8c\x01\n" +
	"\x12ListEventsResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.coloc.EventR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x94\x03\n" +
	"\x12UpdateEventRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"event_date\x18\x05 \x01(\tH\x02R\teventDate\x88\x01\x01\x12\x1f\n" +
	"\blocation\x18\x06 \x01(\tH\x03R\blocation\x88\x01\x01\x12\x1b\n" +
	"\x06budget\x18\a \x01(\x01H\x04R\x06budget\x88\x01\x01\x12\x1c\n" +
	"\afund_id\x18\b \x01(\tH\x05R\x06fundId\x88\x01\x01\x12/\n" +
	"\x06status\x18\t \x01(\x0e2\x12.coloc.EventStatusH\x06R\x06status\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_event_dateB\v\n" +
	"\t_locationB\t\n" +
	"\a_budgetB\n" +
	"\n" +
	"\b_fund_idB\t\n" +
	"\a_status\"I\n" +
	"\x12DeleteEventRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"/\n" +
	"\x13DeleteEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"x\n" +
	"\vRSVPRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.coloc.RSVPStatusR\x06status\"(\n" +
	"\fRSVPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"X\n" +
	"\x16GetParticipantsRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"\xc0\x01\n" +
	"\x17GetParticipantsResponse\x12;\n" +
	"\fparticipants\x18\x01 \x03(\v2\x17.coloc.EventParticipantR\fparticipants\x12\x1f\n" +
	"\vgoing_count\x18\x02 \x01(\x05R\n" +
	"goingCount\x12\x1f\n" +
	"\vmaybe_count\x18\x03 \x01(\x05R\n" +
	"maybeCount\x12&\n" +
	"\x0fnot_going_count\x18\x04 \x01(\x05R\rnotGoingCount\"\xf1\x01\n" +
	"\x10EventParticipant\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_nom\x18\x02 \x01(\tR\auserNom\x12\x1f\n" +
	"\vuser_prenom\x18\x03 \x01(\tR\n" +
	"userPrenom\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x122\n" +
	"\vrsvp_status\x18\x05 \x01(\x0e2\x11.coloc.RSVPStatusR\n" +
	"rsvpStatus\x12!\n" +
	"\fresponded_at\x18\x06 \x01(\tR\vrespondedAtB\r\n" +
	"\v_avatar_url\"\xfe\x04\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcolocation_id\x18\x02 \x01(\tR\fcolocationId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x12$\n" +
	"\x0ecreated_by_nom\x18\x04 \x01(\tR\fcreatedByNom\x12*\n" +
	"\x11created_by_prenom\x18\x05 \x01(\tR\x0fcreatedByPrenom\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"event_date\x18\b \x01(\tR\teventDate\x12\x1f\n" +
	"\blocation\x18\t \x01(\tH\x01R\blocation\x88\x01\x01\x12\x1b\n" +
	"\x06budget\x18\n" +
	" \x01(\x01H\x02R\x06budget\x88\x01\x01\x12\x1c\n" +
	"\afund_id\x18\v \x01(\tH\x03R\x06fundId\x88\x01\x01\x12*\n" +
	"\x06status\x18\r \x01(\x0e2\x12.coloc.EventStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12.\n" +
	"\tuser_rsvp\x18\x0f \x01(\x0e2\x11.coloc.RSVPStatusR\buserRsvp\x12\x1f\n" +
	"\vgoing_count\x18\x10 \x01(\x05R\n" +
	"goingCount\x12\x1f\n" +
	"\vmaybe_count\x18\x11 \x01(\x05R\n" +
	"maybeCount\x12&\n" +
	"\x0fnot_going_count\x18\x12 \x01(\x05R\rnotGoingCountB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_locationB\t\n" +
	"\a_budgetB\n" +
	"\n" +
	"\b_fund_id\"d\n" +
	"\x15DiscoverEventsRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x127\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x18.coloc.DiscoverEventTypeR\teventType\"\xd5\x01\n" +
	"\x0fDiscoveredEvent\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x19\n" +
	"\x05price\x18\x05 \x01(\x01H\x00R\x05price\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x06 \x01(\tH\x01R\x03url\x88\x01\x01\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06sourceB\b\n" +
	"\x06_priceB\x06\n" +
	"\x04_url\"o\n" +
	"\x16DiscoverEventsResponse\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.coloc.DiscoveredEventR\x06events\x12%\n" +
	"\x0esearch_summary\x18\x02 \x01(\tR\rsearchSummary*\x98\x01\n" +
	"\vEventStatus\x12\x1c\n" +
	"\x18EVENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_STATUS_UPCOMING\x10\x01\x12\x18\n" +
	"\x14EVENT_STATUS_ONGOING\x10\x02\x12\x1a\n" +
	"\x16EVENT_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16EVENT_STATUS_CANCELLED\x10\x04*\x88\x03\n" +
	"\x11DiscoverEventType\x12#\n" +
	"\x1fDISCOVER_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bDISCOVER_EVENT_TYPE_CONCERT\x10\x01\x12\"\n" +
	"\x1eDISCOVER_EVENT_TYPE_EXPOSITION\x10\x02\x12 \n" +
	"\x1cDISCOVER_EVENT_TYPE_FESTIVAL\x10\x03\x12\x1d\n" +
	"\x19DISCOVER_EVENT_TYPE_SPORT\x10\x04\x12\x1f\n" +
	"\x1bDISCOVER_EVENT_TYPE_THEATRE\x10\x05\x12#\n" +
	"\x1fDISCOVER_EVENT_TYPE_GASTRONOMIE\x10\x06\x12\x1e\n" +
	"\x1aDISCOVER_EVENT_TYPE_MARCHE\x10\a\x12\x1e\n" +
	"\x1aDISCOVER_EVENT_TYPE_CINEMA\x10\b\x12\"\n" +
	"\x1eDISCOVER_EVENT_TYPE_CONFERENCE\x10\t\x12\x1e\n" +
	"\x1aDISCOVER_EVENT_TYPE_SOIREE\x10\n" +
	"*r\n" +
	"\n" +
	"RSVPStatus\x12\x1b\n" +
	"\x17RSVP_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RSVP_STATUS_GOING\x10\x01\x12\x15\n" +
	"\x11RSVP_STATUS_MAYBE\x10\x02\x12\x19\n" +
	"\x15RSVP_STATUS_NOT_GOING\x10\x032\xdc\a\n" +
	"\fEventService\x12m\n" +
	"\vCreateEvent\x12\x19.coloc.CreateEventRequest\x1a\f.coloc.Event\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/api/v1/colocations/{colocation_id}/events\x12i\n" +
	"\bGetEvent\x12\x16.coloc.GetEventRequest\x1a\f.coloc.Event\"7\x82\xd3\xe4\x93\x021\x12//api/v1/colocations/{colocation_id}/events/{id}\x12u\n" +
	"\n" +
	"ListEvents\x12\x18.coloc.ListEventsRequest\x1a\x19.coloc.ListEventsResponse\"2\x82\xd3\xe4\x93\x02,\x12*/api/v1/colocations/{colocation_id}/events\x12r\n" +
	"\vUpdateEvent\x12\x19.coloc.UpdateEventRequest\x1a\f.coloc.Event\":\x82\xd3\xe4\x93\x024:\x01*\x1a//api/v1/colocations/{colocation_id}/events/{id}\x12}\n" +
	"\vDeleteEvent\x12\x19.coloc.DeleteEventRequest\x1a\x1a.coloc.DeleteEventResponse\"7\x82\xd3\xe4\x93\x021*//api/v1/colocations/{colocation_id}/events/{id}\x12v\n" +
	"\x04RSVP\x12\x12.coloc.RSVPRequest\x1a\x13.coloc.RSVPResponse\"E\x82\xd3\xe4\x93\x02?:\x01*\":/api/v1/colocations/{colocation_id}/events/{event_id}/rsvp\x12\x9c\x01\n" +
	"\x0fGetParticipants\x12\x1d.coloc.GetParticipantsRequest\x1a\x1e.coloc.GetParticipantsResponse\"J\x82\xd3\xe4\x93\x02D\x12B/api/v1/colocations/{colocation_id}/events/{event_id}/participants\x12q\n" +
	"\x0eDiscoverEvents\x12\x1c.coloc.DiscoverEventsRequest\x1a\x1d.coloc.DiscoverEventsResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/events/discoverB7Z5github.com/MarinaGenestoux/application-coloc/proto/pbb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_event_proto_goTypes = []any{
	(EventStatus)(0),                // 0: coloc.EventStatus
	(DiscoverEventType)(0),          // 1: coloc.DiscoverEventType
	(RSVPStatus)(0),                 // 2: coloc.RSVPStatus
	(*CreateEventRequest)(nil),      // 3: coloc.CreateEventRequest
	(*GetEventRequest)(nil),         // 4: coloc.GetEventRequest
	(*ListEventsRequest)(nil),       // 5: coloc.ListEventsRequest
	(*ListEventsResponse)(nil),      // 6: coloc.ListEventsResponse
	(*UpdateEventRequest)(nil),      // 7: coloc.UpdateEventRequest
	(*DeleteEventRequest)(nil),      // 8: coloc.DeleteEventRequest
	(*DeleteEventResponse)(nil),     // 9: coloc.DeleteEventResponse
	(*RSVPRequest)(nil),             // 10: coloc.RSVPRequest
	(*RSVPResponse)(nil),            // 11: coloc.RSVPResponse
	(*GetParticipantsRequest)(nil),  // 12: coloc.GetParticipantsRequest
	(*GetParticipantsResponse)(nil), // 13: coloc.GetParticipantsResponse
	(*EventParticipant)(nil),        // 14: coloc.EventParticipant
	(*Event)(nil),                   // 15: coloc.Event
	(*DiscoverEventsRequest)(nil),   // 16: coloc.DiscoverEventsRequest
	(*DiscoveredEvent)(nil),         // 17: coloc.DiscoveredEvent
	(*DiscoverEventsResponse)(nil),  // 18: coloc.DiscoverEventsResponse
}
var file_event_proto_depIdxs = []int32{
	0,  // 0: coloc.ListEventsRequest.status:type_name -> coloc.EventStatus
	15, // 1: coloc.ListEventsResponse.events:type_name -> coloc.Event
	0,  // 2: coloc.UpdateEventRequest.status:type_name -> coloc.EventStatus
	2,  // 3: coloc.RSVPRequest.status:type_name -> coloc.RSVPStatus
	14, // 4: coloc.GetParticipantsResponse.participants:type_name -> coloc.EventParticipant
	2,  // 5: coloc.EventParticipant.rsvp_status:type_name -> coloc.RSVPStatus
	0,  // 6: coloc.Event.status:type_name -> coloc.EventStatus
	2,  // 7: coloc.Event.user_rsvp:type_name -> coloc.RSVPStatus
	1,  // 8: coloc.DiscoverEventsRequest.event_type:type_name -> coloc.DiscoverEventType
	17, // 9: coloc.DiscoverEventsResponse.events:type_name -> coloc.DiscoveredEvent
	3,  // 10: coloc.EventService.CreateEvent:input_type -> coloc.CreateEventRequest
	4,  // 11: coloc.EventService.GetEvent:input_type -> coloc.GetEventRequest
	5,  // 12: coloc.EventService.ListEvents:input_type -> coloc.ListEventsRequest
	7,  // 13: coloc.EventService.UpdateEvent:input_type -> coloc.UpdateEventRequest
	8,  // 14: coloc.EventService.DeleteEvent:input_type -> coloc.DeleteEventRequest
	10, // 15: coloc.EventService.RSVP:input_type -> coloc.RSVPRequest
	12, // 16: coloc.EventService.GetParticipants:input_type -> coloc.GetParticipantsRequest
	16, // 17: coloc.EventService.DiscoverEvents:input_type -> coloc.DiscoverEventsRequest
	15, // 18: coloc.EventService.CreateEvent:output_type -> coloc.Event
	15, // 19: coloc.EventService.GetEvent:output_type -> coloc.Event
	6,  // 20: coloc.EventService.ListEvents:output_type -> coloc.ListEventsResponse
	15, // 21: coloc.EventService.UpdateEvent:output_type -> coloc.Event
	9,  // 22: coloc.EventService.DeleteEvent:output_type -> coloc.DeleteEventResponse
	11, // 23: coloc.EventService.RSVP:output_type -> coloc.RSVPResponse
	13, // 24: coloc.EventService.GetParticipants:output_type -> coloc.GetParticipantsResponse
	18, // 25: coloc.EventService.DiscoverEvents:output_type -> coloc.DiscoverEventsResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_event_proto_msgTypes[0].OneofWrappers = []any{}
	file_event_proto_msgTypes[2].OneofWrappers = []any{}
	file_event_proto_msgTypes[4].OneofWrappers = []any{}
	file_event_proto_msgTypes[11].OneofWrappers = []any{}
	file_event_proto_msgTypes[12].OneofWrappers = []any{}
	file_event_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
